### ISSUE TITLE
RA en sitio wen

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-balam#1]
[Practica 5 RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-balam/files/11124721/Practica.5.RA.pdf)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by josealfredo79** [comment]
Calificacion 19
